// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


import java.util.HashMap;
import java.util.Map;

public class TestikTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testik() {
    driver.get("https://www.zippyjot.com/");
    driver.manage().window().setSize(new Dimension(550, 699));
    driver.findElement(By.linkText("Log In")).click();
    driver.findElement(By.name("username")).sendKeys("ruzalina15");
    driver.findElement(By.name("password")).sendKeys("030703");
    driver.findElement(By.cssSelector(".ui-button-text")).click();
  }
}
